version: "3.7"

services:
  web:
    stdin_open: true
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - "/usr/srs/app/node_modules"
      - "./:/usr/srs/app"
    container_name: risk_place_website